### ISSUE TITLE
Could you support .net core 2.0?

### ISSUE THREAD

**Issue by forconz** [MarkLTX/TracerX#2]
rt

**Comment by forconz** [comment]
https://archive.codeplex.com/?p=tracerx
Latest logger version: 7.0
Latest viewer version: 7.0

but the version of link:https://www.codeproject.com/Articles/23424/TracerX-Logger-and-Viewer-for-NET
Download source code for TracerX 6.1 - 841 KB
Download binaries for TracerX 6.1 - 441 KB
Compiled help for TracerX-Logger.dll 6.1 - 444 KB

Why not use same version number ?

**Comment by MarkLTX** [comment]
I'm not sure what it would take to support .NET Core.  I have only ever worked with .NET Framework.  I don't personally need support for .NET Core yet so it isn't a priority for me.  Sorry.  Would you like to help?

As for the version numbers, I just need to update the article on CodeProject to have the latest version.  The latest version is 7.0 which you can get it here or at the CodePlex site.  The CodePlex site has compiled binaries if you don't want to build the source.  The source code on CodePlex and GitHub is essentially identical, at least for now.  

The CodeProject site still has the old 6.1 version but the documentation there (i.e. the article itself) is pretty good.  I believe every feature described there still exists in the 7.0 version of the logger.

There are some minor bugs fixed in 7.0 but the main thing you get with 7.0 is the TracerX-Service which allows you to view logs remotely without having to create or use a share on the server where the logs exist.  It is very nice to be able to run the viewer on your local computer, connect to a remote computer (that's running the TracerX-Service), see a list of available log files/folders, and just click on one to view the log (which updates live in the viewer).

**Comment by MarkLTX** [comment]
I just visited the CodePlex site and it looks like they've made the binaries I published there inaccessible.  You can "download the archive" and a get a ZIP file that may contain the binaries but I couldn't find them.

**Comment by delfuria** [comment]
@MarkLTX i would like to help you for creating a .NET Core version of the V7.
Once you will be ready for release a stable version i could take a look at your code and study how to make it "truly" portable using .NET Core.
Thanks

**Comment by delfuria** [comment]
Hi, any news about release date of new version ?
Thanks

**Comment by MarkLTX** [comment]
@delfuria I consider the current release/version to be stable.  It would be great if you could determine the feasibility of targeting .NET Core.  

I think it only makes sense to do this for the TracerX-Logger project, not TracerX-Viewer or TracerX-Service.  Do you agree?

Would the .NET Core version just be another build configuration or would a new solution and/or project be required?

Thanks for your interest in TracerX.

**Comment by BasanthCruz** [comment]
@MarkLTX @delfuria Hi All,  Are you guys working on porting TracerX-Logger project to .Net Core 2.0?

If so please let me know.
Thanks

**Comment by delfuria** [comment]
@BasanthCruz @MarkLTX  HI, i have created a Fork of this repository and i'm refactoring the code for porting it to .NET standard 2.0.
https://github.com/delfuria/TracerX
Actually i have successfully ported TracerX-Logger and Common creating 2 new project with .NET at the end of the project.
Working on convert the service implementation from WCF to gRPC.
